#############################################################
#
# pass to subdirectories
#
#############################################################

SUBDIRS = obj Pho utils MetModel

include SoftRelTools/standard.mk






